name: variables and secrets
env: 
  WF_VAR: "Workflow level variable"
on:
  push:
jobs:
  test_expressions: 
    name: job to test expression
    runs-on: ubuntu-latest
    env: 
      aBoolean: ${{ false }}
      aNull: ${{ null }}
      aNumber: ${{ 42 }}
      aString: this is a string
    steps:
      - name: test null
        if: (env.anull == null)
        run: echo this variable is null
      - name: test boolean
        if: ${{ fromJSON(env.aBoolean) }}
        run: echo this job wont run as our variable is false
      - name: contains function
        if: ${{ contains(env.aString, 'this') }}
        run: |
          echo "Our string var contains the word this"
          echos "but here is a typo that will make this step fal"
      - name: test status check and format function
        if: ${{ failure() }}
        env:
          FORMAT_VAR: ${{ format('Github {0} {1} {2}', 'actions', 'is', 'awesome') }}
        run: |
          echo "this step runs a special script to clean up after failed step"
          echo ${{ env_FORMAT_VAR }}
      - name: function and always status check
        if: ${{ startWith(env.string, 'this') && always() );
        run: sleep 60
      - name: test cancel status check
        if: ${{ cancelled() }}
        run: echo "this job run if a worklow is cancelled, it can also be used for clean-up scrips"
        
  test_variables:
    if: (github.event_name == 'pull_request')
    env:
      JOB_VAR: "Job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
    - name: test variables
      id: stepVar
      env:
        STEP_VAR: "Step level vaiable"
      run: |
        echo ${{ github.actor}}
        echo $GITHUB.JOB
        echo $WF_VAR
        echo @ JOB_VAR
        echo @ STEP_VAR
        echo @{{ vars.CONF_VAR }}
        echo ${{ secrets.A_SECRET }}
           
