name: variables and secrets

env: 
  WF_VAR: "Workflow level variable"

on:
  push:

jobs:
  test_variables:
    env:
      JOB_VAR: "Job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: steVar
        env:
          STEP_VAR: "Step level vaiable"
        run: |
          echo ${{ github.actor}}
          echo $GITHUB.JOB
          echo $WF_VAR
          echo @ JOB_VAR
          echo @ STEP_VAR
          echo @{{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
           
